spring.application.name=springsecurity
spring.datasource.url=jdbc:postgresql://localhost:5432/  #give yourdatabasename here
spring.datasource.username=# give your yourdatabase rootname 
spring.datasource.password=#your password name give here
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
